// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sanlog.EntityFrameworkCore;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(SanlogDbContext))]
    partial class SanlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sanlog.LoggingApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Application", "Environment", "TenantId")
                        .IsUnique();

                    b.ToTable("LogApps");
                });

            modelBuilder.Entity("Sanlog.LoggingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("EventName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoggingLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Version")
                        .HasMaxLength(43)
                        .IsUnicode(false)
                        .HasColumnType("varchar(43)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("LoggingLevelId");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("Sanlog.LoggingError", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HResult")
                        .HasColumnType("int");

                    b.Property<string>("HelpLink")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LogEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentExceptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(2147483647)
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TargetSite")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LogEntryId");

                    b.HasIndex("ParentExceptionId");

                    b.ToTable("LogErrors");
                });

            modelBuilder.Entity("Sanlog.LoggingLevel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LogLevels");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Trace"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Debug"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Information"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Warning"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Error"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Critical"
                        });
                });

            modelBuilder.Entity("Sanlog.LoggingScope", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LogEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LogEntryId");

                    b.ToTable("LogScopes");
                });

            modelBuilder.Entity("Sanlog.LoggingTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientDescription")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("LogTenants");
                });

            modelBuilder.Entity("Sanlog.LoggingApplication", b =>
                {
                    b.HasOne("Sanlog.LoggingTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanlog.LoggingEntry", b =>
                {
                    b.HasOne("Sanlog.LoggingApplication", null)
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sanlog.LoggingLevel", null)
                        .WithMany()
                        .HasForeignKey("LoggingLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanlog.LoggingError", b =>
                {
                    b.HasOne("Sanlog.LoggingEntry", null)
                        .WithMany("Errors")
                        .HasForeignKey("LogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sanlog.LoggingError", null)
                        .WithMany("InnerException")
                        .HasForeignKey("ParentExceptionId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("Sanlog.LoggingScope", b =>
                {
                    b.HasOne("Sanlog.LoggingEntry", null)
                        .WithMany("Scopes")
                        .HasForeignKey("LogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanlog.LoggingEntry", b =>
                {
                    b.Navigation("Errors");

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("Sanlog.LoggingError", b =>
                {
                    b.Navigation("InnerException");
                });
#pragma warning restore 612, 618
        }
    }
}
