// <auto-generated />
using System;
using Leviasan.Sanlog.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leviasan.Example.WebApplication.Migrations
{
    [DbContext(typeof(SanlogDbContext))]
    partial class SanlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Leviasan.Sanlog.LoggingApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Application", "Environment")
                        .IsUnique();

                    b.ToTable("LogApps");
                });

            modelBuilder.Entity("Leviasan.Sanlog.LoggingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("EventName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LogLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasMaxLength(43)
                        .IsUnicode(false)
                        .HasColumnType("varchar(43)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("DateTime");

                    b.HasIndex("LogLevelId");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("Leviasan.Sanlog.LoggingError", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HResult")
                        .HasColumnType("int");

                    b.Property<string>("HelpLink")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LogEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentExceptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(2147483647)
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TargetSite")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LogEntryId");

                    b.HasIndex("ParentExceptionId");

                    b.ToTable("LogErrors");
                });

            modelBuilder.Entity("Leviasan.Sanlog.LoggingLevel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LogLevels");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Trace"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Debug"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Information"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Warning"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Error"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Critical"
                        });
                });

            modelBuilder.Entity("Leviasan.Sanlog.LoggingScope", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LogEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LogEntryId");

                    b.ToTable("LogScopes");
                });

            modelBuilder.Entity("Leviasan.Sanlog.LoggingEntry", b =>
                {
                    b.HasOne("Leviasan.Sanlog.LoggingApplication", "Application")
                        .WithMany("LogEntries")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leviasan.Sanlog.LoggingLevel", "LogLevel")
                        .WithMany("LogEntries")
                        .HasForeignKey("LogLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("LogLevel");
                });

            modelBuilder.Entity("Leviasan.Sanlog.LoggingError", b =>
                {
                    b.HasOne("Leviasan.Sanlog.LoggingEntry", "LogEntry")
                        .WithMany("Errors")
                        .HasForeignKey("LogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leviasan.Sanlog.LoggingError", "ParentException")
                        .WithMany("InnerException")
                        .HasForeignKey("ParentExceptionId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("LogEntry");

                    b.Navigation("ParentException");
                });

            modelBuilder.Entity("Leviasan.Sanlog.LoggingScope", b =>
                {
                    b.HasOne("Leviasan.Sanlog.LoggingEntry", "LogEntry")
                        .WithMany("Scopes")
                        .HasForeignKey("LogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogEntry");
                });

            modelBuilder.Entity("Leviasan.Sanlog.LoggingApplication", b =>
                {
                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("Leviasan.Sanlog.LoggingEntry", b =>
                {
                    b.Navigation("Errors");

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("Leviasan.Sanlog.LoggingError", b =>
                {
                    b.Navigation("InnerException");
                });

            modelBuilder.Entity("Leviasan.Sanlog.LoggingLevel", b =>
                {
                    b.Navigation("LogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
